### ISSUE TITLE
Android Love ETA?

### ISSUE THREAD

**Issue by roblav96** [NathanWalker/nativescript-fancyalert#1]
Any word on an ETA for some Android love? 💘

**Comment by NathanWalker** [comment]
Here is the android plugin to use: https://android-arsenal.com/details/1/4236

Hopefully can integrate over next couple weeks 👍

**Comment by asaph26** [comment]
Any updates on the ETA for Android?

**Comment by NathanWalker** [comment]
@roblav96 @asaph26 --
@bradmartin just swooped into with a ton of :heart: here. Android support just merged. I'll post an update tomorrow with the official support and close this at that time. 👍

**Comment by NathanWalker** [comment]
`1.1.0` published now with Android support. Please see [here](https://github.com/NathanWalker/nativescript-fancyalert/blob/master/fancyalert.android.ts) for supported methods on Android. Thanks again @bradmartin !!

**Comment by asaph26** [comment]
Thank you.
