### ISSUE TITLE
Will the Android support be improved?

### ISSUE THREAD

**Issue by Cayan** [NathanWalker/nativescript-fancyalert#13]
I would like to use this component but I really need the text field.

**Comment by HenriqueMatias** [comment]
+1

**Comment by smarza** [comment]
I would like that too! ;)

**Comment by jimmirbn** [comment]
+1

**Comment by alexandruantonica** [comment]
I would like that too! 👍

**Comment by AlanChauchet** [comment]
Yes, that would be great to have android support for text field

**Comment by alexandruantonica** [comment]
@NathanWalker Is the Android support improved ?
