### ISSUE TITLE
Do you have any examples using regular Javascript?

### ISSUE THREAD

**Issue by d3mac123** [NathanWalker/nativescript-fancyalert#24]
I have not idea how to convert the TS files to JS. Any pointers you can provide?

Thanks!
Alex

**Comment by inviso** [comment]
var falert = require("nativescript-fancyalert");
falert.TNSFancyAlert.showSuccess('Success!', 'Fancy alerts are nice.', 'Yes they are!');

i don't know how to deal with text inputs though...
