### ISSUE TITLE
How to build locally?

### ISSUE THREAD

**Issue by svzi** [NathanWalker/nativescript-fancyalert#27]
I want to make some improvements on the Android part for this plugin. Sadly I don't get it to compile on my local machine. I forked this repository and checked it out. When I run `npm run setup`, `tsc` is reporting some issues::

```
error TS2318: Cannot find global type 'Array'.

error TS2318: Cannot find global type 'Boolean'.

error TS2318: Cannot find global type 'Function'.

error TS2318: Cannot find global type 'IArguments'.

error TS2318: Cannot find global type 'Number'.

error TS2318: Cannot find global type 'Object'.

error TS2318: Cannot find global type 'RegExp'.

error TS2318: Cannot find global type 'String'.


3   public action: Function;
                   ~~~~~~~~

common.ts(3,18): error TS4031: Public property 'action' of exported class has or is using private name 'Function'.


170   public static showCustomButtons(buttons: Array<TNSFancyAlertButton>, image: any, color: string, title: string, subTitle?: string, closeBtnTitle?: string, duration?: number, width?: number) {
                                               ~~~~~

fancyalert.ios.ts(170,44): error TS4070: Parameter 'buttons' of public static method from exported class has or is using private name 'Array'.


180   public static showCustomTextAttributes(attributionBlock: Function, button: TNSFancyAlertButton, image: any, color: string, title: string, subTitle?: string, closeBtnTitle?: string, duration?: number, width?: number) {
                                                               ~~~~~~~~

fancyalert.ios.ts(180,60): error TS4070: Parameter 'attributionBlock' of public static method from exported class has or is using private name 'Function'.
```

Any help would be really much appreciated.

I use TypeScript version 2.4.2 together with NPM 5.3.0 on Mac OS X. What else do you need to know?

Best,
Sven

**Comment by EduhCosta** [comment]
I have the same problem!! ˆˆ

**Comment by svzi** [comment]
Could you please help us @NathanWalker ?

**Comment by bradmartin** [comment]
https://github.com/NathanWalker/nativescript-fancyalert/pull/29 @svzi this should help

**Comment by svzi** [comment]
That looks very promising @bradmartin ! I hope that will get merged soon, because I want to submit my local modifications based on your PR.

**Comment by bradmartin** [comment]
Go for it @svzi 👍

**Comment by NathanWalker** [comment]
I was on vacation when you posted this. Brad saved day thank you!

**Comment by trusktr** [comment]
Regarding the all-too-common error "has or is using private name", I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822
