### ISSUE TITLE
After updating to 3.3.0, Cocoapods error

### ISSUE THREAD

**Issue by d3mac123** [NathanWalker/nativescript-fancyalert#33]
I keep getting this error, after updating to {N} 3.3.0:
`Unable to apply changes on device: 3FD0BDA8-3461-4E92-A2FB-03CC5CE81BFE. Error is: nativescript-fancyalert has Podfile and you don't have Cocoapods installed or it is not configured correctly. Please verify Cocoapods can work on your machine..`

Any ideas on how to fix it?

**Comment by NathanWalker** [comment]
N/A in latest.
