### ISSUE TITLE
showCustomButtons not a function when run in Android API26

### ISSUE THREAD

**Issue by denniscolinares** [NathanWalker/nativescript-fancyalert#35]
Hi,

I get an error regarding the showCustomButtons function.
showCustomButtons functioning properly in iOS Device (iPhone 7+ v11.1)
showCustomButtons not a function when run in Android API26

{N}: 3.3.0
tns-core-module: 3.3.0
tns-ios: 3.3.0
tns-android: 3.3.1
nativescript-fancyalert: 1.1.2

**Comment by Ablankzin** [comment]
Android does not support this method. See [here](https://github.com/NathanWalker/nativescript-fancyalert/blob/master/fancyalert.android.ts) the list of supported methods in android.

**Comment by NathanWalker** [comment]
Thank you @Ablankzin 👍
