### ISSUE TITLE
Using .then after alert shown 

### ISSUE THREAD

**Issue by kentplaza** [NathanWalker/nativescript-fancyalert#4]
How can we use .then after alert?
nsFancyAlert.TNSFancyAlert.showSuccess('Success!', 'Your data has been changed.', 'Close');.then(function(){
  //do something
});

for dialog, we can have a call a function 'OK' clicked.

**Comment by leocaseiro** [comment]
I think you meant callback, or Promise? Is that right?

**Comment by kentplaza** [comment]
yes. that is my point.

**Comment by NathanWalker** [comment]
Hi @kentplaza the native lib (CocoaPod) does not provide a callback when the dialog closes therefore this will not be supported at the moment. 
You could fork the [CocoaPod](https://github.com/dogo/SCLAlertView) and provide that implementation detail and then this plugin could use that modified pod.

**Comment by onury** [comment]
Use `TNSFancyAlert.showCustomButtons()` method instead. And use `action` callback of the custom botton(s).

```js
    let buttons = [
        new TNSFancyAlertButton({ label: "OK", action: () => { console.log("OK"); } })
    ];
    TNSFancyAlert.showCustomButtons(buttons, "some-image", "#00ff00", "Success", "sub-title.");
```
