### ISSUE TITLE
nativescript_fancyalert_1.TNSFancyAlert.showCustomButtons is not a function

### ISSUE THREAD

**Issue by kumarandena** [NathanWalker/nativescript-fancyalert#41]
Hi Nathan,

I have encountered with mentioned typo error when i tried with TNSFancyAlert.showCustomButtons,
If i tried with other fancyalerts, then all works fine.
- Nativescript Angular
- platform - Android

`JS: ERROR TypeError: nativescript_fancyalert_1.TNSFancyAlert.showCustomButtons is not a function
JS: ERROR CONTEXT [object Object]`
 
This is how i implement,

**html.**
`<ActionBar class="action-bar">
    <ActionItem icon="res://ic_notifications_none" (tap)="showCustomButtons()"></ActionItem>
</ActionBar>`

**ts.**
` getOptions(){

let buttons = [
new TNSFancyAlertButton({ label: 'Add Finding', action: () => { console.log('Add Finding'); this.addfinding(); } }),
new TNSFancyAlertButton({ label: 'Save', action: () => { console.log('Save'); this.goAudithome(); } }),
new TNSFancyAlertButton({ label: 'Home', action: () => { console.log('Three'); } })
];
TNSFancyAlert.showCustomButtons(buttons, undefined, undefined, 'Got Buttons?', Add as many as you'd like., 'Ok');

}`

Thanks.

**Comment by Ablankzin** [comment]
The showCustomButtons are not implemented in android, only for iOS.

**Comment by NathanWalker** [comment]
Thanks @Ablankzin Android is a bit more limited however a new `showColorDialog` was just added for android which adds a few more options you can try out.

**Comment by MetaiR** [comment]
for those have this problem
I did this:
```
tns platform clean android
tns run android
```
and it works

**Comment by mhtsharma948** [comment]
Having the same issue. Is it implemented for android now?
