### ISSUE TITLE
Change the font size of the text in the alert

### ISSUE THREAD

**Issue by ngunhaSO** [NathanWalker/nativescript-fancyalert#44]
Is there a way to customize the font size in the alert?

TNSFancyAlert.showCustomButtons(buttons, "some-image", "#387EF5", "Status", "this is the text that i wanna change the font size");

**Comment by NathanWalker** [comment]
@ngunhaSO you can now apply custom fonts and text display options in v3.0.5 on iOS.
See the new `textDisplayOptions`. 👍
