### ISSUE TITLE
Stop action until click OK or CANCEL

### ISSUE THREAD

**Issue by kefahB** [NathanWalker/nativescript-fancyalert#49]
Hello,

Thank you for your plugin is very cool :-)

I have à question, do you think we can stop the code (ex: show a msg in a fancyalert and then when we click OK we can fire navigate with topmost)

Thanks.

**Comment by NathanWalker** [comment]
@kefahB sorry for delayed response and thank you. Android allows this and on iOS just use `TNSFancyAlertButton` as it allows an `action` to be configured which you can use to fire something after the button is acted on and the modal closes.
