### ISSUE TITLE
Vanilla javascript examples?

### ISSUE THREAD

**Issue by sm1ddy** [NathanWalker/nativescript-fancyalert#5]
Nice plugin :)

Just wondering if there were any plans for documentation or support regarding use in vanilla javascript.

**Comment by NathanWalker** [comment]
Hi @sm1ddy sorry for late reply!
You can use in a vanilla js project like this:

```
var fa = require('nativescript-fancyalert');
var TNSFancyAlert = fa.TNSFancyAlert;
var TNSFancyAlertButton = fa.TNSFancyAlertButton;
```

**Comment by sm1ddy** [comment]
Fantastic, thanks Nathan! :)

**Comment by inviso** [comment]
is there a way in NativeScript - Javascript to deal with textfields?
