### ISSUE TITLE
Applicable for different font style

### ISSUE THREAD

**Issue by LSmint** [NathanWalker/nativescript-fancyalert#51]
Thanks to contribute such a nice features! If it can apply with font style then will be more awesome

**Comment by NathanWalker** [comment]
@LSmint you can now apply custom fonts and text display options in v3.0.5 on iOS.
See the new `textDisplayOptions`. 👍

**Comment by NathanWalker** [comment]
Limited on Android so now way to customize there yet but give iOS a try.
