### ISSUE TITLE
fancyalert not working on Android

### ISSUE THREAD

**Issue by tingfong214** [NathanWalker/nativescript-fancyalert#57]
```
TNSFancyAlert.showSuccess(
      "Success!",
      "Fancy alerts are nice.",
      "Yes they are!"
).then(() => {
      console.log("success")
}).catch(err => {
      console.log(err)
})
```

the err response is:
[TypeError: cn.refactor.lib.colordialog.PromptDialog is not a constructor]

Did I do something wrong?

**Comment by tingfong214** [comment]
It works charming after running this:

```rm -rf platforms/android```

removing android in platforms of your file

**Comment by larssn** [comment]
Could you close the issue then?
