### ISSUE TITLE
How to set the icon?

### ISSUE THREAD

**Issue by fransyozef** [NathanWalker/nativescript-fancyalert#59]
I have a fancy alert with timer (showCustomButtonTimer), but I want the icon in the circle  that is used in showSuccess function. How do I set it?

Using this code right now :

        TNSFancyAlert.showCustomButtonTimer(
            0,
            true,
            undefined,
            "green",
            "Mission Impossible",
            `This will self-destruct in 5 seconds.`,
            "Ok"
          );

**Comment by NathanWalker** [comment]
A lot of the methods are convenient method wrappers around others that create the alert. To customize further best to look at the methods available and configure a custom fancy alert based on your needs given all the options 👍
