### ISSUE TITLE
More documentation TNSFancyAlertButton?

### ISSUE THREAD

**Issue by fransyozef** [NathanWalker/nativescript-fancyalert#61]
Are there more properties on a TNSFancyAlertButton? For example, how can I set the background-color?

**Comment by NathanWalker** [comment]
New with v3.0.5 you can now use it's `applyStyle(btn: SLCButton) => void` method which hands you the underlying native fancy alert button which you can style with any standard iOS properties like backgroundColor etc. See the docs just added about it here:
https://github.com/NathanWalker/nativescript-fancyalert/commit/878995e18d9321b0109869753f60ec6c5a6d3089

**Comment by adfdev** [comment]
Have tried with this code:
`          applyStyle: btn => {
            btn.buttonFormatBlock = () => {
              return new NSDictionary(
                [new Color("#ffffff").ios],
                ["backgroundColor"]
              );
            };
          }`

but not work, I developed in nativescript-vue
