### ISSUE TITLE
JS ERROR ReferenceError: Can't find variable: SCLAlertViewHideAnimation

### ISSUE THREAD

**Issue by jorgeucano** [NathanWalker/nativescript-fancyalert#7]
HI, i'm use nativescript with angular 2 and have this error

**Dec  5 18:11:18 MacBook-Pro-de-Jorge com.apple.CoreSimulator.SimDevice.13D875B1-1AB7-4822-8252-9B7B3AF09FC4.launchd_sim[10856] (UIKitApplication:org.nativescript.MiWhatIt[0x7bda][17133]): Service exited due to Segmentation fault: 11
file:///app/tns_modules/nativescript-fancyalert/fancyalert.js:158:43: JS ERROR ReferenceError: Can't find variable: SCLAlertViewHideAnimation**

In the  app.module.ts import
`import { TNSFancyAlert, TNSFancyAlertButton } from 'nativescript-fancyalert';`

and declare in my import

```
imports: [
            NativeScriptModule,
            NativeScriptRouterModule,
            NativeScriptRouterModule.forRoot(router),
            TNSFancyAlert,
            TNSFancyAlertButton
            ]

```
After user in my component

first import  => 

`import { TNSFancyAlert, TNSFancyAlertButton } from 'nativescript-fancyalert';`

and in a function use => 
`TNSFancyAlert.showSuccess('Success!', 'Fancy alerts are nice.', 'Yes they are!');`

Thanks in advance

**Comment by NathanWalker** [comment]
Hi @jorgeucano, don't place `TNSFancyAlert` and friends in `imports`.
In fact, don't declare them at all with angular at all. They are just static javascript classes :)

Just import and use where you need them:
```
import { TNSFancyAlert, TNSFancyAlertButton } from 'nativescript-fancyalert';

TNSFancyAlert.showSuccess('Success!', 'Fancy alerts are nice.', 'Yes they are!');
```

Also, ensure you have **first** run `tns emulate ios` in your project. Very specifically must be that command to ensure CocoaPods are installed properly. After `tns emulate ios` has at least been run once, you can then use other `tns` commands.

Also lemme know your cocoapods version:
```
sudo gem list cocoapods
```

**Comment by MentalRender** [comment]
Hi @NathanWalker , I had the same error as jorgeucano.

After install it with npm, I just import **TNSFancyAlert** and **TNSFancyAlertButton** where I need and run **tns emulate ios**. I have this error:

`Could not find module 'nativescript-fancyalert'`

when I run sudo gem list cocoapods:
```
cocoapods (1.1.1)
cocoapods-core (1.1.1)
cocoapods-deintegrate (1.0.1)
cocoapods-downloader (1.1.2)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.0.0)
cocoapods-trunk (1.1.1)
cocoapods-try (1.1.0)
```

**Comment by jorgeucano** [comment]
**Ok, i remove of import and the list is this** 

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /Developer/android/sdk in PATH, mode 040777

*** LOCAL GEMS ***

cocoapods (1.0.1)
cocoapods-core (1.0.1)
cocoapods-deintegrate (1.0.0)
cocoapods-downloader (1.0.0)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.0.0)
cocoapods-trunk (1.0.0)
cocoapods-try (1.0.0)

**But i have the some problem**

```
Successfully synced application org.nativescript.MiWhatIt on device 13D875B1-1AB7-4822-8252-9B7B3AF09FC4.
Executing before-watch hook from /Users/jorgeucano/Documents/cursos/nativescript/code/MiWhatIt/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 2.0.10
objc[18623]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11cd7f998) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x11cba4d38). One of the two will be used. Which one is undefined.
1   0x1068da5dc -[TNSRuntime executeModule:referredBy:]
2   0x10647f652 main
3   0x10a99668d start
4   0x1
file:///app/tns_modules/nativescript-fancyalert/fancyalert.js:158:43: JS ERROR ReferenceError: Can't find variable: SCLAlertViewHideAnimation
Dec  5 19:40:20 MacBook-Pro-de-Jorge com.apple.CoreSimulator.SimDevice.13D875B1-1AB7-4822-8252-9B7B3AF09FC4.launchd_sim[10856] (UIKitApplication:org.nativescript.MiWhatIt[0xc31d][18623]): Service exited due to Segmentation fault: 11
7:40:21 PM - Compilation complete. Watching for file changes.
```

**Comment by jorgeucano** [comment]
**ok, for me work 👍  ...** 

**_For the doc:_**

import with:
"npm install nativescript-fancyalert --save"

And in the **COMPONENT**
add: 

```
import { TNSFancyAlert, TNSFancyAlertButton } from 'nativescript-fancyalert';

TNSFancyAlert.showSuccess('Success!', 'Fancy alerts are nice.', 'Yes they are!');
```

**Comment by NathanWalker** [comment]
Yes @jorgeucano that is correct, the `--save` is important as NativeScript uses package dependencies to determine how to build the native project. If it's not indicated in the package, it won't install the pods ;)
