### ISSUE TITLE
Not working in iOS after update to version 3.0.9

### ISSUE THREAD

**Issue by xubmuajkub** [NathanWalker/nativescript-fancyalert#79]
@NathanWalker 
After update to `v3.0.9,` it works fine on android but seems like it's not working in iOS. Any solution?

I'm using NS next version `6.1.0`

_Originally posted by @xubmuajkub in https://github.com/NathanWalker/nativescript-fancyalert/issues/76#issuecomment-519009242_

**Comment by OPADA-Eng** [comment]
Can you please explain more about your issue.
What is the error message? 
package.json content?
iOS version you are working on?

**Comment by xubmuajkub** [comment]
@OPADA-Eng 
Thanks for responding, I'm using nativescript-vue with the {N}@next version `(6.1.0)` that the fancy alert has the problem with android, so after update to version `3.0.9` the problem was solve on android. Yet on iOS the Fancy Alert is not popup like on android. It shows nothing and no any error code logged in console either.
**My dependecies**
`
```json
"tns-ios": {
      "version": "6.1.0-2019-08-01-122621-01"
},
"tns-android": {
      "version": "6.1.0-2019-07-29-182447-01"
}
"tns-core-modules": "^6.1.0-next-2019-07-24-141042-01"
```
`
**My code**
`
```vue
TNSFancyAlert.showError(
         this.$t('login.error_message.error'),
         this.$t('login.error_message.not_found'),
         this.$t('btn_label.ok')
).then(() => {});
```
`

I'm not sure about the iOS version but I'm testing on iOS version 12 on both emulator and physical devices.
Hope that you can help me figure it out!

**Comment by xubmuajkub** [comment]
@OPADA-Eng After catching the error I found this in the log
`[ReferenceError: Can't find variable: SCLAlertView]`

**Comment by xubmuajkub** [comment]
OK, seems like the problems come from the old version. I just remove the node_module, platform and hook folder and rebuild and it works fine. Thanks for supporting
