### ISSUE TITLE
How do you add an image in showColorDialog for android?

### ISSUE THREAD

**Issue by dimitriospafos** [NathanWalker/nativescript-fancyalert#82]
How do I pass the "contentImage?" argument in showColorDialog?

 showColorDialog(
    title: string,
    subTitle: string,
    okBtnTitle?: string,
    cancelBtnTitle?: string,
    backgroundColor?: string,
    titleTextColor?: string,
    contextTextColor?: string,
    contentImage?: any
  ): Promise<any>;

I tried to pass the name of an image which exists in assets ? (e,g image.png) but it didn't work.

**Comment by Rahul1d** [comment]
Hi @dimitriospafos,
You cannot pass image as string. You need to pass it as a resource.

You can use the following code;

```
var app = require("tns-core-modules/application"); 
var context = app.android.context;
var image = "@drawable/ image.png".
           
 var  resId = context.getResources().getIdentifier(image,null, context.getPackageName());

```

**Comment by dimitriospafos** [comment]
@Rahul1d thanks this worked.
