### ISSUE TITLE
When is coming new version for N 7 ?

### ISSUE THREAD

**Issue by Slymn10** [NathanWalker/nativescript-fancyalert#88]

**Comment by AgustinV08** [comment]
This plugin works with Nativescript 7

**Comment by JJVetter** [comment]
I just tried it with NS7 and it failed because it is still using tns-core-modules

**Comment by NathanWalker** [comment]
Published here now (compat with 7, 8 and beyond):
https://www.npmjs.com/package/@nstudio/nativescript-fancyalert

Source managed here now:
https://github.com/nstudio/nativescript-plugins/tree/master/packages/nativescript-fancyalert
