### ISSUE TITLE
Nativescript 8.x

### ISSUE THREAD

**Issue by biospank** [NathanWalker/nativescript-fancyalert#89]
Hey @NathanWalker, is there any plan to port this plugin to {N} 8.x?

Cheers

**Comment by JJVetter** [comment]
+1

**Comment by NathanWalker** [comment]
Yes - sorry for delay, had notifications off here. We’re going to move this under @nstudio scope and publish a major by end of this week.

**Comment by NathanWalker** [comment]
Published here now (compat with 7, 8 and beyond):
https://www.npmjs.com/package/@nstudio/nativescript-fancyalert

Source managed here now:
https://github.com/nstudio/nativescript-plugins/tree/master/packages/nativescript-fancyalert
