### ISSUE TITLE
XCODE error: framework not found SCLAlertView_Objective_C

### ISSUE THREAD

**Issue by MentalRender** [NathanWalker/nativescript-fancyalert#9]
Hi, I have this error only when xcode build my app  😕 

`ld: warning: directory not found for option '-F/Users/mntlrndr/Library/Developer/Xcode/DerivedData/myApp-aderpffvcdpoooblbbmauqxaixld/Build/Products/Debug-iphoneos/SCLAlertView-Objective-C'
ld: framework not found SCLAlertView_Objective_C
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Its perfect in my iPhone emulator (tns emulate ios). I'm use NativeScript with Angular 2. Cocoapods version:
```
cocoapods (1.1.1)
cocoapods-core (1.1.1)
cocoapods-deintegrate (1.0.1)
cocoapods-downloader (1.1.2)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.0.0)
cocoapods-trunk (1.1.1)
cocoapods-try (1.1.0)
```

Thanks in advance

**Comment by NathanWalker** [comment]
Hi @MentalRender when using CocoaPods, NativeScript generates 2 xcode project files (this is common to any standard iOS project btw), 1 `.xcodeproj` file, and 1 `.xcworkspace` file. Only ever open the `.xcworkspace` file when working within XCode when your project has CocoaPods; it's the only way to build successfully in XCode. 👍
